# Generated by Django 4.0.3 on 2022-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
