# Generated by Django 4.0.3 on 2022-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_code_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='questions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
