# Generated by Django 4.0.3 on 2022-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_alter_code_code_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user_details',
            name='about_us',
            field=models.TextField(blank=True),
        ),
    ]
